
/*
 * CATEGORY ITEM
 */
export const ADD_CATEGORY_ITEM = 'ADD_CATEGORY_ITEM';
export const DELETE_CATEGORY_ITEM = 'DELETE_CATEGORY_ITEM';
export const EDIT_CATEGORY_ITEM = 'EDIT_CATEGORY_ITEM';

/*
 * ENTRY CATEGORY
 */
export const ADD_ENTRY_CATEGORY = 'ADD_ENTRY_CATEGORY';
export const DELETE_ENTRY_CATEGORY = 'DELETE_ENTRY_CATEGORY';
